version: '3'
services:
  listener:
    build: listener
    network_mode: host
    depends_on: [redis]
  sender:
      build: sender
      network_mode: host
      depends_on: [redis]
  redis:
    image: redis
    ports:
        - "6379:6379"