name: Gen Docs

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python environment
      uses: actions/setup-python@v1.1.1
    - uses: actions/checkout@v2
    - name: Install grip
      run: |
        python -m pip install --upgrade pip
        pip install grip
    - name: Convert
      run: |
        mkdir html
        grip README.md --title=Welcome --export html/!welcome.html
        grip labs/lab0/README.md --title="Lab 0"  --export html/lab0.html
        grip labs/lab1/README.md --title="Lab 1"  --export html/lab1.html
        grip labs/lab2/README.md --title="Lab 2"  --export html/lab2.html
        grip labs/lab3/README.md --title="Lab 3"  --export html/lab3.html
        grip labs/lab4/README.md --title="Lab 4"  --export html/lab4.html
        grip labs/lab5/readme.md --title="Lab 5"  --export html/lab5.html
        grip messaging/README.md --title="Messaging" --export html/messaging.html

        cp -rf messaging/*.png html
        cp -rf labs/lab5/*.jpg html
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: html
        # Directory containing files to upload
        path: html
